name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  thavixt-uikit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List directories in the repository
        run: |
          ls -d ${{ github.workspace }}/*/
      - run: echo "ğŸ This job's status is ${{ job.status }}."
